defaults:
  - _self_
  - /callbacks: [checkpoint_every_n_steps, checkpoint_monitor, learning_rate_monitor]
  - /data: acyp
  - /model: medium
  - /strategy: ddp
  - /noise: loglinear
  - /lr_scheduler: constant_warmup
  - /classifier_model: null
  - /guidance: null
mode: train # train / train_classifier / ppl_eval
diffusion: uniform #absorbing_state
backbone: dit # dit / dimamba / ar
classifier_backbone: null
parameterization: d3pm #subs # subs / d3pm / ar
time_conditioning: True #False #Use for UDLM
subs_masking: False
zero_recon_loss: True # Use for UDLM
T: 0 # 0 (continuous time) / 1000
is_vision: False
seed: 1
loader:
  global_batch_size: 48 #32 takes 40.5 GB on the small model variant (time: 2 AM 8 June)
  eval_global_batch_size: ${.global_batch_size}
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: ${div_up:${.global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  eval_batch_size: ${div_up:${.eval_global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  num_workers: ${eval:"len(__import__('os').sched_getaffinity(0))"}
  pin_memory: False #True
  persistent_workers: False ##True was default
sampling:
  use_cache: True
  steps: 128
  # Note: batch_size is **per machine**
  batch_size: ${loader.eval_batch_size}
  num_sample_batches: 4 # Total samples: `num_gpus` * `batch_size` * `num_sample_batches`
  use_float64: False
training:
  ema: 0.9999
  antithetic_sampling: True
  importance_sampling: False
  sampling_eps: 1e-3
  change_of_variables: False
  compute_loss_on_pad_tokens: False
  use_simple_ce_loss: False # Ignore ELBO; just use CE
  guidance: null
  # guidance: # Can turn off with `training.guidance: null`
  #   cond_dropout: 0.0
eval:
  checkpoint_path: /data/dhruva/discrete-diffusion-guidance/outputs/udlm_100k_medium_esm_tok/checkpoints/best.ckpt #path to checkpoint
  disable_ema: False
  generate_samples: True
  generated_samples_path: /data/dhruva/discrete-diffusion-guidance/samples_log/ #"${.save_dir}/samples/"
  use_tensorboard: False
  max_samples: 50_000
# === Sampling Mode ===
sample:
  mode: "uncond" # options: "uncond", "inpaint"
  uncond:
    seq_length: [60, 400] #,200] # Can be a single int or a range
    num_samples: 305000 # Total number of samples to generate
    sampling_batch_size: 10 #12 # Batch size per sampling step
#   # === Inpainting Sampling Parameters ===
#   # Uncomment below to use inpainting mode
#   # inpaint:
#   prior_1: "MKTLL"             # N-terminal prefix (can be empty string "")
#   prior_2: "GHHHHH"            # C-terminal suffix (can be empty string "")
#   mask_len: 20                 # Number of <mask> tokens to fill in
#   num_samples: 32              # Number of inpainted sequences to generate
optim:
  weight_decay: 0
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  num_nodes: 1
  devices: ${device_count:}
  accumulate_grad_batches: ${div_up:${loader.global_batch_size}, ${eval:${trainer.devices} * ${loader.batch_size} * ${trainer.num_nodes}}}
  gradient_clip_val: 1.0
  precision: "bf16-mixed"
  num_sanity_val_steps: 2
  max_steps: 1_000_000
  log_every_n_steps: 10
  limit_train_batches: 1.0 # train on full dataset, can be used to toggle quick run
  limit_val_batches: 1.0 # validate on full dataset, can be used to toggle quick run
  val_check_interval: 450 #10000
wandb:
  project: udlm #discrete-diffusion-guidance
  notes: UDLM on 101K train, 25K val sequences
  group: null
  job_type: training
  name: null
  # Use ID when resuming training from a checkpoint
  # id: ${.name}_${seed}
  tags:
    - ${noise.type}
    - ${data.train}
    - ${data.valid}
hydra:
  run:
    dir: /data/dhruva/discrete-diffusion-guidance/outputs/${now:%Y.%m.%d}/${now:%H%M%S} #./outputs/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true
checkpointing:
  # Use custom `save_dir` if, e.g., saving to S3 bucket, otherwise leave this parameter as is
  save_dir: /data/dhruva/discrete-diffusion-guidance/outputs/udlm_100k_medium_esm_tok
  # Note: `checkpoints` path should correspond to `checkpoint_every_n_steps.dirpath`
  resume_from_ckpt: True
  resume_ckpt_path: ${.save_dir}/checkpoints/last.ckpt
